### ISSUE TITLE
circular structure to JSON error

### ISSUE THREAD

**Issue by grewegreg** [darnton/BlazorDeviceInterop#10]
With the GeoLocation Service version 0.1.2 installed, the error listed below occurs when accessing the GetLocation results: 

> circular structure to JSON
>     --> starting at object with constructor 'Window'
>     --- property 'window' closes the circle
>     at JSON.stringify (<anonymous>)
>     at O (blazor.webassembly.js:1:5193)
>     at blazor.webassembly.js:1:3398

**Code snippets:**
```
private GeolocationResult _CurrentLocation;
        private GeolocationResult CurrentLocation
        {
            get
            {
                if (_CurrentLocation is null)
                {
                    _CurrentLocation = new();
                }

                return _CurrentLocation;
            }
            set
            {
                if (!Equals(_CurrentLocation, value))
                {
                    SolicitationChangedEventArgs eventArgs = new(nameof(CurrentLocation))
                    {
                        NewValue = value,
                        OldValue = _CurrentLocation,
                    };
                    _CurrentLocation = value;
                    OnCustomPropertyChanged(eventArgs);
                }
            }
        }

        protected async Task<GeolocationResult> GetLocation()
        {
            try
            {
                await Task.Yield();
                GeolocationResult retVal = await LocationService.GetCurrentPosition();

                if (retVal != null && retVal.Error is null)
                {
                    return retVal;
                }
                else if (retVal.Error is not null)
                {
                    ApplicationException ex = new(retVal.Error.Message);
                    ex.Data.Add("Error Code", retVal.Error.Code);
                    throw ex;
                }
                else
                {
                    throw new ApplicationException("Unable to retrieve current location.");
                }
            }
            catch (Exception ex)
            {
                ReportError(ex);
                return new GeolocationResult();
            }
        }

        public static string GoogleAddressHelper.GetDirections(MasterFileDto masterFile, GeolocationCoordinates currentLocation)
        {
            GoogleAddress startingAddress = new(currentLocation.Latitude, currentLocation.Longitude);
            return startingAddress.GetDirections(GetGoogleAddress(masterFile, GoogleAddressType.Destination));
        }

 protected override async Task OnInitializedAsync()
        {
            await base.OnInitializedAsync();
            CurrentLocation = await GetLocation();
        }

        protected async Task OnDirectionsClick()
        {
            Console.WriteLine(FormattingUtilities.ModelToJson<GeolocationResult>(CurrentLocation));
            await NavigateToNewTab(GoogleAddressHelper.GetDirections(MasterRecord, CurrentLocation.Position.Coords)); <--Error occurs here
        }

```

**CurrentLocation =** 
> {"Position":{"Coords":{"Latitude":38.95453416666666,"Longitude":-84.67371172222222,"Altitude":null,"Accuracy":275,"AltitudeAccuracy":null,"Heading":null,"Speed":null},"Timestamp":1655594061682},"Error":null}

Details:
Project type: Blazor WASM

Microsoft Visual Studio Community 2022
Version 17.2.4
VisualStudio.17.Release/17.2.4+32602.215
Microsoft .NET Framework
Version 4.8.04161

Installed Version: Community

Visual C++ 2022   00482-90000-00000-AA281
Microsoft Visual C++ 2022

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   17.2.392.13739
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   17.2.392.13739
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.2.392.13739
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.2.0-4.22281.5+8d3180e5f00d42f0f0295165f756f368f0cbfa44
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   17.0.22089.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.2.20 (482eb2a)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.40404.3 Commit Hash:dd524a7d0ee653de8b7b32a93ca22f2d57cd2419
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   6.2.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Python - Profiling support   17.0.22089.1
Profiling support for Python projects.

Python with Pylance   17.0.22089.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Razor (ASP.NET Core)   17.0.0.2218101+885a343b00bcab620a90c1550c37dafd730ce984
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.0.62204.01010
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.10418.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.2.0-4.22281.5+8d3180e5f00d42f0f0295165f756f368f0cbfa44
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.1.0-beta.22274.4+211fd760c2315d73cfa0d375fe64abb346bc1096
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.2.0.177 (d17-2@2f6c881)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.2.0.244 (remotes/origin/d17-2@197e1a0b7)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.2.15 (2e3b60e)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   12.3.3.3 (d17-2/4e061b7)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: dffa5ab
    Java.Interop: xamarin/java.interop/d17-2@9760f0a9
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.38.2@7b1e016
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-2@fc3c2ac

Xamarin.iOS and Xamarin.Mac SDK   15.10.0.5 (96b3edb6d)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by grewegreg** [comment]
Disregard, the issue was problems with literal characters in the URL.
